CREATE DATABASE testcenter;

USE testcenter;

CREATE TABLE clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    hostname VARCHAR(100) UNIQUE,
    ip_address VARCHAR(50),
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255)
);