ALTER TABLE systems
    ADD COLUMN IF NOT EXISTS os_version VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS gpu VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS current_usage VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS reserved_until VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS reinstalled_at VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS info TEXT NULL,
    ADD COLUMN IF NOT EXISTS helpline TEXT NULL;

ALTER TABLE system_status
    ADD UNIQUE KEY IF NOT EXISTS uq_system_status_system_id (system_id);
